
# pubspec.yaml

# Project details
name: gravity_dig
description: Basic game created using Flutter
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

# Project dependencies (external packages/libs)
dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  # CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Flame game engine
  flame: ^0.10.2

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Material Icons font
  uses-material-design: true
  
  # Image and audio assets
  assets:
    - assets/images/backgrounds/01_ground.png
    - assets/images/backgrounds/02_trees.png
    - assets/images/backgrounds/03_distant_trees.png
    - assets/images/backgrounds/07_background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


# EOF

